import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";

import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import PageWrapper from "@/Components/PageWrapper";
import ScrollToTop from "@/Components/ScrollToTop";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" suppressHydrationWarning>
         <head>
            <script
               dangerouslySetInnerHTML={{
                  __html: `
                     try {
                        const theme = localStorage.getItem('theme');
                        if (theme === 'dark') {
                           document.documentElement.classList.add('dark');
                        }
                     } catch (e) {}
                  `,
               }}
            />
         </head>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen bg-zinc-50 dark:bg-[#001d3d]`}>

            {/* 🔥 Theme Provider should wrap whole UI */}
            <ThemeProvider>
               <PageWrapper>
                  {/* Background Blobs */}
                  <div className="absolute inset-0 overflow-hidden -z-10">

                  <div className="absolute top-[-150px] left-[-150px] w-[400px] h-[400px] 
                     bg-purple-300 rounded-full mix-blend-multiply filter blur-3xl opacity-50 
                     dark:bg-purple-600/50">
                  </div>

                  <div className="absolute top-0 right-[-100px] w-[450px] h-[450px] 
                     bg-blue-300 rounded-full mix-blend-multiply filter blur-3xl opacity-40 
                     dark:bg-blue-600/50">
                  </div>

                  <div className="absolute bottom-[-100px] left-1/3 w-[350px] h-[350px] 
                     bg-pink-300 rounded-full mix-blend-multiply filter blur-3xl opacity-60 
                     dark:bg-pink-600/50">
                  </div>
               </div>

               {/* Content */}
               <div className="relative z-10 flex flex-col min-h-screen">

                  {/* Navbar */}
                  <div className="fixed top-0 left-0 w-full z-50 backdrop-blur-md bg-white/70 dark:bg-[#001d3d]/90 border-b border-white/10 shadow-sm">
                     <Navbar />
                  </div>

                  {/* Page Body */}
                  <main className="flex-grow pt-20"> {/* pt-20 -> navbar space fix */}
                     {children}
                  </main>

                  {/* Footer */}
                  <footer className="mt-auto">
                     <Footer />
                  </footer>

               </div>

               {/* Scroll to Top Button */}
               <ScrollToTop />
            </PageWrapper>
            </ThemeProvider>
         </body>
      </html>
   );
}
